SELECT P.WORKER_ID, NAME, SURNAME, P.PALLET_ID, M.SPECIES_ID, PROCEDURE_ID, SCHEDULED_DATE FROM PALLETS P
JOIN WORKERS W on W.WORKER_ID = P.WORKER_ID
JOIN MAINTENANCE M on P.SPECIES_ID = M.SPECIES_ID
JOIN SCHEDULE S2 on M.MAINTENANCE_ID = S2.MAINTENANCE_ID

