--SELECT FOR WORKER
SELECT P.WORKER_ID, NAME, SURNAME, P.PALLET_ID, M.SPECIES_ID, PROCEDURE_ID, SCHEDULE_ID, SCHEDULED_DATE FROM PALLETS P
LEFT JOIN WORKERS W on W.WORKER_ID = P.WORKER_ID
LEFT JOIN MAINTENANCE M on P.SPECIES_ID = M.SPECIES_ID
LEFT JOIN SCHEDULE S2 on M.MAINTENANCE_ID = S2.MAINTENANCE_ID;

--SELECT TO FIND INFO ABOUT PLANTS
SELECT TYPE_, P.PLANT_ID, S.SPECIES_ID, PROCEDURE_ID, FREQUENCY FROM PLANTS P
LEFT JOIN SPECIES S on P.PLANT_ID = S.PLANT_ID
LEFT JOIN MAINTENANCE M on S.SPECIES_ID = M.SPECIES_ID

--SELECT FOR ALL AVAILABLE PROCEDURES
SELECT PROCEDURE_ID, DESCRIPTION FROM PROCEDURES

--SELECT ALL WORKER DATA
SELECT W.WORKER_ID, NAME, SURNAME, AGE, IS_WORKING FROM WORKERS W
LEFT JOIN STATUS S on W.WORKER_ID = S.WORKER_ID

--SELECT SCHEDULE AND ACCORDING REALISATION AND FREQUENCY
SELECT S2.SCHEDULE_ID, SCHEDULED_DATE, REALISATION_ID, REALISATION_DATE, FREQUENCY FROM SCHEDULE S2
LEFT JOIN MAINTENANCE M on S2.MAINTENANCE_ID = M.MAINTENANCE_ID
LEFT JOIN REALISATION R2 on S2.SCHEDULE_ID = R2.SCHEDULE_ID


