ALTER TABLE STATUS
    ADD FOREIGN KEY (WORKER_ID) REFERENCES WORKERS (WORKER_ID)
        ON DELETE CASCADE;

ALTER TABLE PALLETS
    ADD FOREIGN KEY (WORKER_ID) REFERENCES WORKERS (WORKER_ID)
        ON DELETE CASCADE;

ALTER TABLE PALLETS
    ADD FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES (SPECIES_ID)
        ON DELETE CASCADE;

ALTER TABLE SPECIES
    ADD FOREIGN KEY (PLANT_ID) REFERENCES PLANTS (PLANT_ID)
        ON DELETE CASCADE;

ALTER TABLE MAINTENANCE
    ADD FOREIGN KEY (SPECIES_ID) REFERENCES SPECIES (SPECIES_ID)
        ON DELETE CASCADE;

ALTER TABLE MAINTENANCE
    ADD FOREIGN KEY (PROCEDURE_ID) REFERENCES PROCEDURES (PROCEDURE_ID)
        ON DELETE CASCADE;

ALTER TABLE SCHEDULE
    ADD FOREIGN KEY (PALLET_ID) REFERENCES PALLETS (PALLET_ID)
        ON DELETE CASCADE;

ALTER TABLE SCHEDULE
    ADD FOREIGN KEY (MAINTENANCE_ID) REFERENCES MAINTENANCE (MAINTENANCE_ID)
        ON DELETE CASCADE;

ALTER TABLE REALISATION
    ADD FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULE (SCHEDULE_ID)
        ON DELETE CASCADE;
